# Generated by Django 2.0.3 on 2018-04-03 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20180401_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='idUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
